// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnfQ4uGP1r2Ci1n13dgT9wSjyJXEOn9EA',
    appId: '1:330084489717:web:94eabbf19f74379ef968bc',
    messagingSenderId: '330084489717',
    projectId: 'notes-flutter-63933',
    authDomain: 'notes-flutter-63933.firebaseapp.com',
    storageBucket: 'notes-flutter-63933.firebasestorage.app',
    measurementId: 'G-YSS1GMC7HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHkOznSFi7t6fBJZzxRgFkglIGnY1Bko',
    appId: '1:330084489717:android:1d41b9e689b9941ff968bc',
    messagingSenderId: '330084489717',
    projectId: 'notes-flutter-63933',
    storageBucket: 'notes-flutter-63933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fOsU2rxA03zMYLTqfEv1Vbwqmcb3MM8',
    appId: '1:330084489717:ios:29a04118a3a43036f968bc',
    messagingSenderId: '330084489717',
    projectId: 'notes-flutter-63933',
    storageBucket: 'notes-flutter-63933.firebasestorage.app',
    iosBundleId: 'com.laysanha.notes.notesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1fOsU2rxA03zMYLTqfEv1Vbwqmcb3MM8',
    appId: '1:330084489717:ios:29a04118a3a43036f968bc',
    messagingSenderId: '330084489717',
    projectId: 'notes-flutter-63933',
    storageBucket: 'notes-flutter-63933.firebasestorage.app',
    iosBundleId: 'com.laysanha.notes.notesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnfQ4uGP1r2Ci1n13dgT9wSjyJXEOn9EA',
    appId: '1:330084489717:web:b37a1a6b52261c84f968bc',
    messagingSenderId: '330084489717',
    projectId: 'notes-flutter-63933',
    authDomain: 'notes-flutter-63933.firebaseapp.com',
    storageBucket: 'notes-flutter-63933.firebasestorage.app',
    measurementId: 'G-HL6V11T9F2',
  );
}
